HEIGHT_DIVISOR: float = 0.005

MINIMUM_COUNTRY_AREA: int = 10**2
MINIMUM_COUNTRY_HOLE_AREA: int = 2**2

NORMAL_OPEN_GL: bool = True

TRANSLUCENCY_MAP_SUMMAND: float = 0
TRANSLUCENCY_MAP_FACTOR: float = 1

ROUGHNESS_MAP_SUMMAND: float = 0.35
ROUGHNESS_MAP_FACTOR: float = 1
